name: GitHub Action NPM BUILD Test

on:
  push:
    branches: [ act ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Running NPM Install & Build For Gutenberg
        run: |
          npm install --quiet && npm run build
      - name: Running NPM Install & Build for Admin Panel
        run: |
          cd includes/Admin/Settings && npm install --quiet && npm run prod && cd ../../..